# GitHub Actions workflow for RunPod deployment
name: Deploy Flux LoRA Handler to RunPod

on:
  push:
    branches: [main]
    paths: ['runpod-setup/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./runpod-setup
        file: ./runpod-setup/Dockerfile.production
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/flux-lora-trainer:latest
          ${{ secrets.DOCKER_USERNAME }}/flux-lora-trainer:v2-production
          ${{ secrets.DOCKER_USERNAME }}/flux-lora-trainer:${{ github.sha }}
        platforms: linux/amd64
        
    - name: Update RunPod endpoint
      run: |
        echo "🚀 Docker image built and pushed successfully!"
        echo "📝 Next steps:"
        echo "1. Go to RunPod Console → Serverless"
        echo "2. Update your endpoint with image: ${{ secrets.DOCKER_USERNAME }}/flux-lora-trainer:latest"
        echo "3. Ensure GPU types: RTX 4090, RTX A6000"
        echo "4. Test with a small training job"